### ISSUE TITLE
Address vs Endpoint and their semantics

### ISSUE THREAD

**Issue by pavolloffay** [hypertrace/agent-config#30]
Right now we have:

```proto
message Reporting {
    // address represents the host for reporting the traces e.g. api.traceable.ai
    google.protobuf.StringValue address = 1;
```

```proto
message Opa {
    // address represents the host for polling OPA config file e.g. http://opa.traceableai:8181/
    google.protobuf.StringValue address = 1;
```

The address in the reporting is meant to be the only host without port (@jcchavezs can correct me). This brings an interesting limitation for somebody using the (OSS) agent in a custom environment with different port mappings. 

The second point is that all the addresses in the config should be consistent and should have the same semantics (only host, or allow also port or provide full endpoint). 

The question is what we choose? Only host, or host:port or full endpoint e.g. http://here:9411/api/v2/spans.

On top of that our clients use heterogenous reporters (e.g. OTEL, Zipkin, Jaeger). Accepting only host makes it easy to switch the reporter in the agent without breaking the config.

cc) @davexroth

**Comment by davexroth** [comment]
Yeah, this is a little messy, as some backend services such as OPA are REST and some are GRPC so they are configured differently.

I think we should standardize on `endpoint` for the config option.  For REST type endpoints, we can support the config ` http://here:9411/api/v2/spans` and for grpc or tcp endpoints, config such as `there:55690`.

**Comment by jcchavezs** [comment]
> I think we should standardize on endpoint for the config option. For REST type endpoints, we can support the config http://here:9411/api/v2/spans and for grpc or tcp endpoints, config such as there:55690.

I think this is much more confusing as it makes it inconsistent across configuration so I'd rather be more specific than too generic.

@pavolloffay's concern is valid and we need to come up with an approach that works by default (or minimal config change) for 95% percent of the users, still allowing the other 5% to achieve their goals with some additional configuration.

In one hand, using a host (and port potentially) is very restrictive for users as they might now know what is the end URL they are reporting to. For our agents it makes sense as we count in with the fact that there is a collector resolving those requests but it becomes hard if I want to use HT agents to report to another backend (e.g. zipkin, jaeger or datadog).

In the other hand, using the full endpoint is explicit and users know exactly what URL they are calling. However, this means that we might transfer the responsibility of choosing the right URL if for example one agent decides to report over jaeger thrift, then we need to ay users: *"hey use http://here:9411/api/v2/spans for all your services except those using language X agent as they report over jaeger thrift endpoint"*. This problem is easy solvable if we standardise the endpoint we use for reporting.

Despite preferences (disclaimer I am a zipkin member but that does not bias my judgment here) I think if we settle on **all agents reporting over zipkin endpoint** (http://here:9411/api/v2/spans) we don't have to worry about this: users will know exactly what endpoint we are calling, most of tracing backends and the collector itself ingest zipkin data and collector can still ingest different data over different endpoints (for progressive rollout of our agents). This is also coherent with the fact that most of our agents are using zipkin endpoint to report data (whether we like it or not).

Pavol has some concerns around this proposal as zipkin might be the least supported model in OTel (notably because of lack of `resources` for example) but we can fix this upstream if that becomes a problem (we keep saying we want to contribute back to OTel).

As bonus, if we do so it is easy to intercept the calls and reingest reported data over HTTP using zipkin endpoint and a curl call (related to https://github.com/hypertrace/hypertrace/issues/108)

Ping @mohit-a21
